### ISSUE TITLE
Labels are not updated

### ISSUE THREAD

**Issue by and7ey** [jorgemorgado/dashing-barchart#3]
I would like to update not only bar values, but labels as well (the date/time to be displayed there). So, I tried to update the coffee file with the following code:

```
onData: (data) ->
if @myChart && data.datasets && data.labels
    for i in [0..@myChart.datasets.length - 1]
      for j in [0..@myChart.datasets[i].bars.length - 1]
        @myChart.datasets[i].bars[j].value = data.datasets[i].data[j]
        @myChart.datasets[i].bars[j].label = data.labels[i]
    @myChart.update(@myChart)
```

But it didn't help. I tried to check [chartjs documentation](http://www.chartjs.org/docs/#bar-chart), but didn't get if update of labels is supported. 

Is there any way to achieve what I need?

**Comment by jorgemorgado** [comment]
Based on the [Chart.js docs](http://www.chartjs.org/docs/#bar-chart) this option does not seem to be possible. Once the graph is rendered the initial labels remain. Still, you can try to use the methods `.addData(valuesArray, label)` and `.removeData()` to add and remove values/labels on the datasets. I haven't tried this myself so I can't guarantee it will work effectively. You might also direct this question directly to the [Chart.js developers](http://www.chartjs.org/docs/#notes-bugs-&-issues) since this is not related to the widget. In any case I will leave this issue open - if you come up with a good solution, feel free to post it here. I will close the issue then.

**Comment by estel1212** [comment]
is there an idea how to fill Text in the bar?

**Comment by jorgemorgado** [comment]
I've just released the new version with support for Chat.js v2. Not sure if this option is available on the new version of Chart.js but it's the latest version so you might want to try it.
