### ISSUE TITLE
Fix to work with latest Chart.js

### ISSUE THREAD

**Issue by SteveWells** [jorgemorgado/dashing-barchart#8]
I've been using this widget (and line chart), and had to modify them to work with the latest Chart.js. Pretty simple fixes to the coffee script - would you be interested in incorporating them? Happy to contribute....

**Comment by jorgemorgado** [comment]
Hi Steve. Sure, I will happily integrate your changes. I'm not sure if a pull request is the best way to go because I need to review the changes and (if possible/makes sense) try to make them backward compatible. I know the new version has a bunch of new features and need to check how to make them work with both versions. If your changes are simple, just paste them in this issue and I will review them into the widget. If you think a pull request makes more sense, just go that way. In both cases, I will add you name to the authors list ;-) thanks!

**Comment by SteveWells** [comment]
Hi Jorge,

Happy to send the changes and let you check/change them - I'm no expert coffee script programmer so I think that would be the safest way to make sure it all still hangs together....

I'll paste in the changes...

Cheers,

Steve

**Comment by SteveWells** [comment]
To work with the latest Chart.js, I had to modify the call to:

```
@myChart = new Chart(@ctx, {
  type: 'bar',
  data: @myData,
  options: $.extend({
    responsive: false
    barShowStroke: true
    scaleShowVerticalLines: false
    maintainAspectRatio: true,
    legend: {
      display: true
    }
  }, @get('options'))
```

   });

**Comment by jorgemorgado** [comment]
I've just released the new version with support for Chat.js v2. Thanks Steve!
